### ISSUE TITLE
Could not run

### ISSUE THREAD

**Issue by anon11010110** [Eto19/lisk-cracker#1]
Followed the instructions on a fresh install of Windows 10, but crashed when trying to run with the following output:

```
C:\Users\User\Downloads\lisk-cracker>python main.py
--- Lib Initialization 0.1718595027923584 seconds ---
Starting...
(2019, 1, 2)

2019.1.2
3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
LIST OF AVAILABLE CUDA DEVICES :
 -GPU IDX: 0, name: GeForce RTX 2080
   Compute Capability: 7.5
   Total Memory: 8388608 KB
   MULTIPROCESSOR_COUNT: 46
   WARP_SIZE: 32

SELECTED GPU IDX : 0
registers : 65536
shared_memory : 49152

blocks: 23552
block_size: 512
global_size: 12058624
grid: 23552
grid256: 46
gridsha256: 188416

Addresses to search : 1001
bloom_filter_size : 497999

Caching batch_ge_add kernel !
Unexpected error...exiting
Traceback (most recent call last):
  File "main.py", line 635, in <module>
    main()
  File "main.py", line 136, in main
    batch_ge_add = load_module_new('batch_ge_add', batch_ge_add_file, nvcc_options, nvcc_include_dirs, cubin_cache)
  File "C:\Users\User\Downloads\lisk-cracker\lib_ed.py", line 359, in load_module_new
    cubin = pycuda.compiler.compile(module_file, options=nvcc_options, include_dirs=nvcc_include_dirs, cache_dir=None)
  File "C:\Users\User\Anaconda3\lib\site-packages\pycuda\compiler.py", line 254, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "C:\Users\User\Anaconda3\lib\site-packages\pycuda\compiler.py", line 78, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
  File "C:\Users\User\Anaconda3\lib\site-packages\pycuda\compiler.py", line 54, in preprocess_source
    raise CompileError("nvcc preprocessing of %s failed" % source_path,
pycuda.driver.CompileError: nvcc preprocessing of C:\Users\User\AppData\Local\Temp\tmp5yhwnky4.cu failed
[command: nvcc --preprocess -use_fast_math --generate-line-info -arch sm_75 -m64 -IC:\Users\User\Downloads\lisk-cracker/inc_cu -Ic:\users\user\anaconda3\lib\site-packages\pycuda\cuda C:\Users\User\AppData\Local\Temp\tmp5yhwnky4.cu --compiler-options -EP]
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
```

**Comment by Eto19** [comment]
I may have forgot something about the pycuda installation for windows but I'm not sure.

Try installing Visual Studio Community 2017
Download here :
https://visualstudio.microsoft.com/vs/older-downloads/

And add this directory to PATH :
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64`

If this directory doesn’t exist, you will need to determine where your cl.exe was installed. If this directory does exist add it to your PATH

Can you also paste the output of 'nvcc -V' and 'nvidia-smi' to get the cuda version and driver version ?
I'm going to test on a fresh windows 10 install right now, coming back later.

**Comment by anon11010110** [comment]
Thank you.  Changing python from 3.8.3 to 3.7.0 first to better match your setup.  Will get those outputs next too

**Comment by Eto19** [comment]
Tested on fresh windows 10 install, GTX 1080:

- Fresh windows 10 install
- Nvidia driver installed by default: 432.00

- Install https://www.anaconda.com/products/individual 
  filename Anaconda3-2020.07-Windows-x86_64.exe
  Enable "Add Anaconda3 to my PATH environment variable" during installation

- Install https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal
  filename cuda_10.2.89_441.22_win10.exe
  Choose "Express installation" (it should upgrade drivers to 441.22)

- Tried to install pycuda, got an error about missing Build Tools
- Install "Build Tools for Visual Studio 2019" https://visualstudio.microsoft.com/downloads/

- Reboot

- pip install pycuda pynacl
- I tried to run 'python main.py', but I got an error at cubin compilation

- add "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64" to PATH
  (This is where cl.exe should be)

- 'python main.py' works now

**Comment by anon11010110** [comment]
Just added to that path and it seems all good now

Great job

**Comment by seighail3** [comment]
Dont forget 
!pip install numpy pycuda pynacl
